name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VCPKG_BUILD_TYPE: release
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true' # Set to 'recursive' to recursively checkout submodules

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Install dependencies with vcpkg
      run: |
        vcpkg install --triplet arm64-android

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Change wrapper permissions
      run: |
        chmod +x ./android/gradlew

    - name: Build with Gradle
      run: |
        cd android
        ./gradlew build
