name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VCPKG_BUILD_TYPE: release
  # VCPKG_BINARY_SOURCES: "clear;files,${{ github.workspace }}/.vcpkg-cache,readwrite"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true' # Set to 'recursive' to recursively checkout submodules

    - name: Cache vcpkg installed packages
      id: vcpkg-cache
      uses: actions/cache@v4
      with:
        # Cache the vcpkg installed packages (and buildtrees/downloads if you like)
        path: |
          ~/.cache/vcpkg
          ${{ github.workspace }}/vcpkg/packages
        # A key that changes whenever your vcpkg.json (or lockfile) changes
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
      shell: bash

    - name: Install dependencies with vcpkg
      run: |
        ./vcpkg/vcpkg install --triplet arm64-android

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Change wrapper permissions
      run: |
        chmod +x ./android/gradlew

    - name: Build with Gradle
      run: |
        cd android
        ./gradlew build
