name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VCPKG_BUILD_TYPE: release

jobs:
  build_matrix:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            name: linux
            cache_path: /home/runner/.cache/vcpkg/archives
          - os: windows-latest
            name: windows
            cache_path: C:/Users/runneradmin/AppData/Local/vcpkg/archives
          - os: macos-latest
            name: osx
            cache_path: /Users/runner/.cache/vcpkg/archives
        buildType: ["Debug", "Release"]
        shared:    [true, false]
    runs-on: ${{ matrix.platform.os }}
    env:
      # Instruct vcpkg to use (and populate) the platform-specific archive cache
      VCPKG_BINARY_SOURCES: "clear;files,${{ matrix.platform.cache_path }},readwrite"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true' # Set to 'recursive' to recursively checkout submodules

      - name: Cache vcpkg archives
        uses: actions/cache@v4
        with:
          path: ${{ matrix.platform.cache_path }}
          key: ${{ runner.os }}-vcpkg-archives-${{ matrix.buildType }}-${{ matrix.shared }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-archives-

      - name: Ensure vcpkg cache dir exists (Unix)
        if: runner.os != 'Windows'
        run: mkdir -p ${{ matrix.platform.cache_path }}
        shell: bash

      - name: Ensure vcpkg cache dir exists (Windows)
        if: runner.os == 'Windows'
        run: mkdir "${{ matrix.platform.cache_path }}"
        shell: cmd

      - name: Bootstrap vcpkg (Unix)
        if: runner.os != 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
        shell: bash

      - name: Bootstrap vcpkg (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: Install dependencies with vcpkg
        run: ./vcpkg/vcpkg install

      - name: Configure CMake shared=${{ matrix.shared }} with vcpkg dependencies
        run: |
          cmake -B "${{ github.workspace }}/build" \
                -DCMAKE_BUILD_TYPE="${{ matrix.buildType }}" \
                -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" \
                -DBUILD_SHARED_LIBS="${{ matrix.shared }}" \
                -DBUILD_WITH_OPENSSL=ON

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.buildType }}

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -j 8 -C ${{ matrix.buildType }} --output-on-failure
